# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d8eed0553e167438ff1904517e3c647090e7cba7b2d9b0dbdad2e82298f721ea159c2d0ade988133e85ddb1c299defbce8f3130e702bde6803524b7dc491ae

test:
  secret_key_base: 022dcae37f389f26bf44e184d9696709db1963935a3cd9798f48875742320bb05b92d229a53ec65792fd8b174766ab64278d87641a0ad8825bbfce1e5ffabd4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
